### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Daharosh** [ttbagroup/ttbagroup.github.io#6]
- [x]  https://ttbagroup.com/en/marketing-projectssocial-media-marketing-for-pub-in-montreal-2/ - logo doesn't show in the 3rd block

- [x] https://ttbagroup.github.io/en/marketing-for-beauty-salon-ipl-case-study - this page always redirects on live website

- [x] https://ttbagroup.com/en/marketing-services-montreal/seo-search-engine-optimization/ - pub st paul case redirects (on tilda the url is correct, I updated the code on prose, but it never changed on staging site.)

- [x] when a page loads we see objects with no css

- [x] when you share a page, thumbnail for facebook automatically takes the hero image and the title of the page

**Comment by sashakaz** [comment]
- [x] Add "Services" & "Our Team" as submenu items

**Comment by Daharosh** [comment]
- [x] Add back and forth arrows for the projects as well

**Comment by Daharosh** [comment]
* [x] on mobile, submenus dont click

**Comment by dy** [comment]
Done
