### ISSUE TITLE
Fix the "thumbnail" feature when sharing 

### ISSUE THREAD

**Issue by Daharosh** [ttbagroup/ttbagroup.github.io#8]
When I share a link on facebook for example, it shows the thumbnail of a home page with title and meta of the home page.
![screen shot 2017-04-27 at 6 11 23 pm](https://cloud.githubusercontent.com/assets/26447643/25506497/f1974170-2b74-11e7-9d8d-16a182c075bf.png)

**Comment by dy** [comment]
Should work since now
